### ISSUE TITLE
Add option to choose from existing cross section definition

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-schematisation-editor#10]
"There's no possibility to choose an already existing cross section definition. Now every time a pipe is added a new cross section is made, while this is not necessary" [Rebecca]

We will probably need some search/filter functionality to find the cross section definition you need. Some models have many of them.

**Comment by leendertvanwolfswinkel** [comment]
Never heard anyone request this since we removed the option in the geopackage database schema, closing the issue
