### ISSUE TITLE
Facilitate adding structure controls to a schematisation

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#101]
User-friendly tool to replace the (phased-out) 3Di Toolbox "Control structures" tool in the Commands Toolbox

Design TBD

**Comment by Overmeen** [comment]
First quick thoughts:
- I think we can (and should) solve this in Schematisation Editor without a specific tool.
- In the attribute table of each control structure a tab "Control" should be there. The user can select which type of control. One of these type will be to map based on a measurement location (see next bullet). The table feature ( [Water level] | [Crest level] ) would be nice here.
- A new table should arise when loading a schematisation via the Schematisation named "measurement locations". This will contain Point Geometry locations in relation to a (controlled) structure. For now "controls" are linked by grid ID, geometry would be the preferred way. This layer should have a styling with a label that indicates its relation to which structure.
- A styling should make clear which structures are controlled, without losing the specific style for a specific structure. Think about a glance surrounding a structure.

**Comment by leendertvanwolfswinkel** [comment]
Ok based on this I think we should first define what users want, and then try to think of solutions. I read the following in your comment:
- Users want to see on the map canvas which structures have a control associated with them
- Control structures should be persistent, i.e. still work the same after changes to the schematisation have been made (other than changes to the controlled structures or measurement locations themselves)
- Users want to see measurement locations on the map
- Users want to see on the map how measurement locations relate to controls

**Comment by leendertvanwolfswinkel** [comment]
will be taken care of in the new database schema 300. closing this ticket
