### ISSUE TITLE
Missing values in Global Settings make target sqlite unusable

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#104]
If the global settings table contains NULLs for columns that have NOT NULL constraints in de sqlite (e.g. output_time_step), the export will fail and the schema_version will be set to 1. If after that, a user fills in the required values in the geopackage global_settings table and tries to export to spatialite again, export will fail because of an invalid schema version

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Didn't noticed affecting of the `schema_version` value after failure of the export. After fixing missing values export works just fine for me and output Spatialite file is readable by 3Di Toolbox. Another thing is that NOT NULL constrains shouldn't be there anymore, right?

**Comment by leendertvanwolfswinkel** [comment]
Tested, sqlite does not become unusable in my test. I made tickets in `threedi-schema` for removal of `NOT NULL` constraints

No further action needed on this in 3Di Schematisation Editor
