### ISSUE TITLE
Editing attributes of referenced, not yet committed features fails

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#107]
Example:
- Create a manhole on a location where no connection node exists yet
- In the attribute form of the manhole, fill in a value for Node storage area
- Save edits
- An error is produced `Layer Connection Node: Feature -9223372036854775808 for attribute update not found.`
- The features (manhole and connection node) are created, but the value for Node storage area is not saved

The same problem seems to exist for all other cases in which attributes of referenced features are edited before saving the changes

**Comment by ldebek** [comment]
@leendertvanwolfswinkel PR with fix can be found here: https://github.com/nens/threedi-schematisation-editor/pull/112
