### ISSUE TITLE
Consequences of removal of v2_levee table

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#108]
In schema version 214, v2_levee no longer exists. The consequences of this (as I can see, there may be more) are:

- [x] When importing from spatialite, make the table `linear_obstacle` from just the `v2_obstacle` table, instead of `v2_levee` and `v2_obstacle` both
- [x] `linear_obstacle` will have fewer fields. The ones to keep are:

- id
- code
- crest_level
- geom

- [x] When exporting to spatialite, all `linear_obstacle` features should be exported to `v2_obstacle`
- [x] Change the stylings ('default' and 'levels'). New style QMLs: [https://app.zenhub.com/files/481141268/393f5502-1d98-462d-b00a-bef1bdb33af8/download](https://app.zenhub.com/files/481141268/393f5502-1d98-462d-b00a-bef1bdb33af8/download)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Changes added to the PR: https://github.com/nens/threedi-schematisation-editor/pull/111

**Comment by leendertvanwolfswinkel** [comment]
Perfect
