### ISSUE TITLE
Consequences of removal of v2_connected_pnt and v2_calculation_point

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#109]
In schema 214, `v2_connected_pnt` and `v2_calculation_point` tables are removed
- [ ] Remove conversion from `v2_connected_pnt` to `connected_point` when importing from spatialite
- [ ] Remove conversion from `v2_calculation_point` to `calculation_point` when importing from spatialite
- [ ] Remove conversion from `connected_point` to `v2_connected_pnt` to  when exporting to spatialite
- [ ] Remove conversion from `calculation_point` to `v2_calculation_point` to  when exporting to spatialite

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Changes added PR: https://github.com/nens/threedi-schematisation-editor/pull/111

**Comment by leendertvanwolfswinkel** [comment]
Perfect
