### ISSUE TITLE
Add field `max_infiltration_capacity` to simple_infiltration table

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#110]
New schema version (210): added v2_simple_infiltration.max_infiltration_capacity

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Changes added to PR: #111

**Comment by leendertvanwolfswinkel** [comment]
@ldebek the attribute maximum_infiltration_capacity is not shown in the form view of the attribute table, even though the field is there in the table view

**Comment by ldebek** [comment]
@leendertvanwolfswinkel fixed
