### ISSUE TITLE
Dialog for loading a schematisation from 3Di working directory

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#117]
Similar to what we have implemented for loading 3Di results in 3Di Results Analysis: https://github.com/nens/ThreeDiToolbox/issues/721

- [x] The dialog should look like this:
![image](https://user-images.githubusercontent.com/26224299/224658754-9dbc0c06-cf82-4d4d-beec-1ee40349fe7c.png)
(Except that in the screenshot, in some cases there are multiple rows for one combination of schematisations/revision nr., which makes sense for results, but is not possible for schematisations)

- [x] The first tab of the dialog is populated with all the schematisations that are available in the 3Di Working Directory (as defined in the project settings by 3Di Models & Simulations). The list should include revisions in the `revision {n}` folders as well as those in the `work in progress` folders. Please show the revision number for the work in progress folder as `{n} (work in progress)`.

- [x] The second tab should simply contain a QgsFileWidget to select a spatialite from any location the user browses to (i.e. the current implementation)
- [x] Double-clicking a row should also load the schematisation
- [x] If it is known which schematisation revision has been downloaded or created most recently, this one should be highlighted/selected.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Implementation ready for testing is now available on branch: https://github.com/nens/threedi-schematisation-editor/tree/enhancement_117

**Comment by leendertvanwolfswinkel** [comment]
@ldebek excellent, please merge
