### ISSUE TITLE
"Import culverts" processing algorithm

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#127]
Please read #119 first

I propose that before we implement the GUI, we make a processing algorithm that does the same thing. It would work like this:

*Inputs*
- Source layer
- Target 3Di Schematisation (GeoPackage file)
- Conversion configuration file (e.g. JSON)
The JSON file could look something like this:

```
{
  "target_layer": "culvert",
  "conversion_settings": {
    "use_snapping": true,
    "snapping_distance": 0.5,
    "create_connection_nodes": true
  },
  "fields": {
    "id": {
      "method": "auto"
    },
    "code": {
      "method": "source_attribute",
      "source_attribute": "kdu_identificatie",
      "default_value": "duiker (kdu id onbekend)"
    },
    "display_name": {
      "method": "ignore"
    },
    "calculation_type": {
      "method": "source_attribute",
      "source_attribute": "kdu_open",
      "value_map": {
        "ja": "102",
        "nee": "101"
      }
    },
    "discharge_coefficient_positive": {
      "method": "default",
      "default_value": 0.8
    }   
  }
}
```

*Outputs*
- The resulting _Culvert_ and _Connection node_ features are written to the corresponding layers in the geopackage

*Algorithm*
See #119

**Comment by leendertvanwolfswinkel** [comment]
I have tested this, using this example data: [https://app.zenhub.com/files/481141268/b0b34642-e95b-48a8-9fbe-94bfbf5e6c82/download](https://app.zenhub.com/files/481141268/b0b34642-e95b-48a8-9fbe-94bfbf5e6c82/download)

Test results:
- It helped me debug syntax errors in my JSON file, which was perfect
- I had a lot of duplicate connection nodes 
- No culvert features where added to the geopackage
- Map canvas is not repainted after the algo finishes, so it looks like nothing has happened

**Comment by ldebek** [comment]
Fixes applied.

**Comment by leendertvanwolfswinkel** [comment]
Great, I think the main things are there now. Some smaller issues (I hope):
- [ ] My config json includes `create_connection_nodes` in the `conversion_settings`, but if I set it to `False`, it will still create connection nodes
- [ ] If a source value is `NULL`, please use the `default_value` as fallback value. For example, if in the source data the value for `afvoercoefficient` is `NULL` and this is the config for `discharge_coefficient_positive`
```
"discharge_coefficient_positive": {
      "method": "source_attribute",
      "source_attribute": "afvoercoefficient",
      "default_value": 0.8
	},
``` 
the imported culvert should have a `discharge_coefficient_positive` of 0.8. Now it is NULL

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Fixes for the above issues applied.

**Comment by leendertvanwolfswinkel** [comment]
Great! Let's merge this
