### ISSUE TITLE
Processing algorithm Generate Exchange lines improvements

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#131]
- [x] For the input 'Input Channel Layer', use the Channel layer that is loaded through the Schematisation Checker as the default
- [x] Same for 'Exchange lines layer'
- [x] Limit the number of exchange lines per channel (differs per calculation type): 
 - Max 1 for 'Connected'
 - Max 2 for 'Double connected'
 - Max 0 for Isolated or Embedded
If no exchange line can be generated anymore because these maxima are exceeded, show an error: 
"Error: channel {id} with calculation type {calculation_type} already has a maximum of {0|1|2} exchange lines. Change the calculation type or remove exchange lines for this channel and try again." The error should not stop the algorithm.
- [x] This requires the 'Exchange line' to have a `channel_id`, and the 'Channel' to have an `id` and `calculation_type`. Checking these things in `checkParameterValues` has the additional benefit that we limit the risk that users choose the wrong inputs

**Comment by leendertvanwolfswinkel** [comment]
Please also make sure the new Processing Algorithms group uses the same icon as the '3Di' group. Currently, the icon is smaller:

![image.png](https://images.zenhubusercontent.com/62bedb7b667872a01ff3bdff/d2209fdb-c1de-4e2e-8b73-680b8213e98a)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel PR with requested changes: https://github.com/nens/threedi-schematisation-editor/pull/132

**Comment by leendertvanwolfswinkel** [comment]
All the issues in this ticket are fixed, but...

Now the whole algorithm doesn't work anymore, because I get this error:

```
Could not commit changes to layer Exchange line

Errors: ERROR: 1 feature(s) not added.
  
  Provider errors:
      OGR error creating feature -7021: failed to prepare SQL: INSERT INTO "exchange_line" ( "geom", "id", "channel_id", "exchange_level") VALUES (?, ?, ?, ?) - undersize RTree blobs in "rtree_exchange_line_geom_node"
```

I also committed some changes to the user feedback messages, please have a look at those changes.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Could you please send me info about QGIS build you are using with libs listed? It doesn't look like a problem with an algorithm itself, but with writing data to the Geopackage file. Isn't some other process accessing while you are trying to use algorithm? Btw. I'm not experiencing such issue on my QGIS 3.28.
