### ISSUE TITLE
Add vegetation rasters and settings table to project

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#145]
Add the vegetation_drag table to the settings group as 'Vegetation drag settings'

If the `global_settings` table references a record in the `vegetation_drag` table that references a raster in the columns `vegetation_height_file`, `vegetation_stem_count_file`, `vegetation_stem_diameter_file`, and/or `vegetation_drag_coefficient_file`, those rasters should also be added to the qgis project.

Names & units:

- Vegetation stem count [-]
- Vegetation stem diameter [m]
- Vegetation drag coefficient [-]
- Vegetation height [m]

Styling files: 
[https://app.zenhub.com/files/481141268/75f7abc2-f04e-4714-b498-7edbf736d07f/download](https://app.zenhub.com/files/481141268/75f7abc2-f04e-4714-b498-7edbf736d07f/download)

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I have tested this, and it works as it should, except for the styling. Please style the vegetation rasters using the qml files in the zip https://app.zenhub.com/files/481141268/75f7abc2-f04e-4714-b498-7edbf736d07f/download

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Styling is fixed now.

**Comment by leendertvanwolfswinkel** [comment]
Perfect; please merge
