### ISSUE TITLE
Attributes are NULLed when connection node is moved

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#162]
See this video: https://we.tl/t-OlZmQHF4vd

In this case, the connection_node_end_id is NULLed. 

Another client reported that for pump stations, the pump capacity was NULLed. This may be a very different issue, or the same. I propose to first fix the issue that is shown in the video. Then I will check if this has also solved the pump capacity issue.

**Comment by leendertvanwolfswinkel** [comment]
I tried moving a connection node to which a surface map was linked; the issue still exists for this case
For pipes and pumps, everything works fine.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Fix for the surface map links was added.
