### ISSUE TITLE
Culverts importer: value map UI

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#174]
Put a push button in the _value map_ cells instead of the current text edit widget.

If no value map has been set yet, the push button text should be "Set...". 
If a value map has been set, it can display it in JSON format `{"Rond": 2, "Rechthoekig": 0, "Eivormig": 3, "Onbekend": "NULL"}` (show only the part of the text that fits on the button). 

If user clicks the button, show a dialog to define the value map. The dialog should have:
- Button "Load from source layer". If the user clicks this, the "Source attribute value" column should be filled with unique values from chosen source layer's field.
- A table widget with columns "Source attribute value" and "Target attribute value".
- UI to add and delete rows 
- OK / Cancel buttons

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I have tested this, Can you please make the following changes:
- For the attribute "Friction type", I have specified the source attribute ("type ruwheid") in the main dialog. When I click on the value map button > Load from source layer, I am asked to choose the source attribute. Can you change this so that if the source attribute was already specified, it uses that to fill the value map keys?
- When using "Load from source layer", some keys (source attribute values) may already be present in the value map. It should only add the new keys, instead of the current behaviour that results in duplicate keys.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Requested changes/fixes applied.

**Comment by leendertvanwolfswinkel** [comment]
@ldebek Sleep-deprived or not, you delivered it :) well done
