### ISSUE TITLE
Support 1D vegetation in Schematisation Editor

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#188]
In schema version 219, the following new fields where added to the spatialite:

v2_cross_section_location (these are all float fields)
- vegetation_stem_density
- vegetation_stem_diameter
- vegetation_height
- vegetation_drag_coefficient

v2_cross_section_definition (these are all string fields containing space-separated float values)
- friction_values 
- vegetation_stem_densities
- vegetation_stem_diameters
- vegetation_heights
- vegetation_drag_coefficients

- [ ] Import/export to spatialite should be added. 
- [ ] The attribute form of Cross-section location should be changed as shown in the images below
- [ ] The "friction values per segment" and all vegetation options should only be enabled if cross section shape = YZ and friction_type = Chézy with conveyance.
- [ ] The "friction values per segment" and "vegetation parameters per segment" tables should have 1 fewer row than the "cross-section table"

<img width="1312" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMldYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6229029a85d6ecfcc25a1ace5a8ee2679aae94a/image.png" alt="image.png" />
<img width="635" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmFYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ce3df5f723d88d10a03e8b409c20f1796051dfd/image.png" alt="image.png" />
<img width="607" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmlYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9108cba3e99d351e647acb9365a72d0a909177d8/image.png" alt="image.png" />

**Comment by leendertvanwolfswinkel** [comment]
I tested your updated version; I think we are almost there. w.r.t. the scrollbars, see my explanation on Slack.

W.r.t. the radio buttons / checkable group idea: I think we can do without it as you mentioned that is is quite complicated to implement. To make it clear to the user how it works, we can just change the text "Friction coefficients per segment" to "Friction coefficients per segment (overrides single friction value)" and "Vegetation parameter per segment" to "Vegetation parameters per segment (overrides single vegetation values)"

However, I found another (important) issue; the vegetation values from v2_cross_section_location are not imported correctly:

<img width="1748" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHRiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9da27e62ac823ef647399e3b4232bd84e91e360b/image.png" alt="image.png" />

**Comment by leendertvanwolfswinkel** [comment]
I did further testing and had some discussions with my colleague. I have identified the following to do's:
- [ ] Tables are cleared, but upon committing the changes, the data comes back. 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDlrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d8322b0288e006427b5a0dfc304751e6179a235/table%20cannot%20really%20be%20cleared.mp4)
- [ ] I like the more compact view and that you can see 5 rows without scrolling; but I think it would be better that if there are more rows, the scrollbar **is** shown
- [ ] A new version of `threedi-schema`, 0.219.3 was released today. It correctly regenerates the `v2_cross_section_location_view`. Please bump the version number in both `threedi-schematisation-editor` and in [this PR of `ThreeDiToolbox`](https://github.com/nens/ThreeDiToolbox/pull/995)
- [ ] Apparently the logic of which combinations of cross-section shapes, friction types and friction/vegetation parameters are allowed is a bit more complicated than I thought before. This is the full thing:

Cross-section shape = YZ
	Chezy:
		(This is already implemented correctly)
		-> Single friction value ENABLED
		-> Friction coefficients per segment DISABLED
		-> Single vegetation parameters ENABLED
		-> Vegetation parameters per segment DISABLED
	Manning:
		-> Single friction value ENABLED
		-> Friction coefficients per segment DISABLED
		-> **Single vegetation parameters DISABLED**
		-> Vegetation parameters per segment DISABLED
	Chezy with conveyance:
		-> Single friction value ENABLED
		-> Friction coefficients per segment ENABLED
		-> **Single vegetation parameters DISABLED**
		-> Vegetation parameters per segment ENABLED
	Manning with conveyance
		-> Single friction value ENABLED
		-> Friction coefficients per segment ENABLED
		-> **Single vegetation parameters DISABLED**
		-> Vegetation parameters per segment DISABLED

Cross-section shape = Tabulated rectangle, Tabulated trapezium
	Chezy:
		-> Single friction value ENABLED
		-> Friction coefficients per segment DISABLED
		-> **Single vegetation parameters DISABLED**
		-> Vegetation parameters per segment DISABLED
	Manning:
		-> Single friction value ENABLED
		-> Friction coefficients per segment DISABLED
		-> **Single vegetation parameters DISABLED**
		-> Vegetation parameters per segment DISABLED
	Chezy with conveyance:
		-> Single friction value ENABLED
		-> Friction coefficients per segment DISABLED
		-> Single vegetation parameters ENABLED
		-> Vegetation parameters per segment DISABLED
	Manning with conveyance
		-> Single friction value ENABLED
		-> Friction coefficients per segment DISABLED
		-> **Single vegetation parameters DISABLED**
		-> Vegetation parameters per segment DISABLED

Cross-section shape anything else, all friction types
		-> Single friction value ENABLED
		-> Friction coefficients per segment DISABLED
		-> **Single vegetation parameters DISABLED**
		-> Vegetation parameters per segment DISABLED

**Comment by ldebek** [comment]
@leendertvanwolfswinkel  `Tables are cleared, but upon committing the changes, the data comes back.` issue was skipped for a time beign as we discussed.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel [Threedi](https://github.com/nens/ThreeDiToolbox/pull/995) PR reffers to the threedi-schema 0.219.*, so that shouldn't be any action required (only creation of the fresh build might be needed).

**Comment by leendertvanwolfswinkel** [comment]
@ldebek ok I re-ran the github action for it. I'll test asap!
