### ISSUE TITLE
Processing algorithm to link (impervious) surfaces to connection nodes

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#191]
Inputs:
- (Impervious) surface layer
- (Impervious) surface map layer
- Pipe layer
- Connection node layer
- Sewerage types (list of checkable items; by default only "stormwater" and "combined" are checked)
- Stormwater sewer preference [m] 
- Sanitary sewer preference [m]
- Search distance

Algorithm:
- For each Surface polygon, find the nearest Pipe within search distance
- Include only the pipe types checked in "Sewerage types"
- When comparing the distances, subtract  "Stormwater sewer preference" from the distance to stormwater sewers 
- Same for sanitary sewers
- Find the closest point from the surface on the nearest pipe
- Find out which of the pipe's connection nodes is nearest to this closest_point
- Create a surface mapping from the surface to that connection node. 
- Fill in the attributes. Percentage = 100.

Output:
- No new layer is created, just features added to the Surface layer

**Comment by leendertvanwolfswinkel** [comment]
@ldebek some feedback from testing:
- Please change the algorithm name to "Map (impervious) surfaces to connection nodes"
- Sewerage types "stormwater" should also be checked by default
- Performance needs to be improved. Probably indexing the geometries would speed things up considerably? 
- Should be possible to cancel the algorithm during execution
- Please show a progress bar with percentages

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Requested changes applied.

**Comment by leendertvanwolfswinkel** [comment]
@ldebek perfect, great stuff. this will make quite a few people happy.

I added documentation in the shortHelpString and renamed 0D to Inflow (naming things...)

Please merge :)
