### ISSUE TITLE
Cross section location should be placeable on channel segment, not just on channel vertex

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#196]
When this feature was first developed, 3Di required cross section locations to be exactly on a channel vertex. This has changed, it is now allowed to place it on segments also. 

The behaviour of the Schematisation Editor should reflect this, in the snapping options and also when you place a cross section location on a channel segment, its channel_id should be updated.

**Comment by leendertvanwolfswinkel** [comment]
I can indeed place a cross-section location on a channel segment now, but it behaves differently in terms of filling in  the attributes. If I place it on a vertex, the channel ID and many other values are filled in automatically. If I place it on a segment, this is not the case.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Reported issues should be fixed now.
