### ISSUE TITLE
Processing algorithm "Manhole bottom level from pipes"

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#209]
**Input**
- Manhole layer
- Pipe layer
- Boolean option "overwrite existing bottom levels"
- Boolean option "do not raise existing bottom levels"

**Output**
- No new layer, just updating the "bottom_level" attribute of the input Manhole layer

**Algorithm**
- For each manhole, find the adjacent pipe invert levels (e.g. `pipe.invert_level_start_point where manhole.connection_node_id == pipe.connection_node_start_id` or `pipe.invert_level_end_point where manhole.connection_node_id == pipe.connection_node_end_id`)
- Calculate the minimum of the adjacent pipe invert levels; if "do not raise existing bottom levels" is True, also include the current bottom level value in the list of values for which you calculate the minimum
- Fill in this value in the manhole layer
- If "overwrite existing values" is False, only run the algorithm for manhole features where Manhole.bottom_level is NULL; else, run it for all manholes

**Comment by jordienetten** [comment]
Please also for Culverts :-)

**Comment by ldebek** [comment]
Tool ready for testing on branch: https://github.com/nens/threedi-schematisation-editor/tree/manhole_bottom_level_from_pipes

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I made a PR from your branch

Some feedback:
- With these settings, manholes with bottom level NULL are not updated: <img width="1005" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL214QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7bf5cc59c64ecc79281807aff5a4016672fedf66/image.png" alt="image.png" />
- If I have a pipe with invert_level_start_point = 2.0 and invert_level_end_point = 3.0, the algo fills in bottom_level = 2.0 for both manholes; the start manholes should get 2.0 and the end manhole 3.0 as bottom level
- Please allow users to choose "selected features only" for both pipes and manholes
- Set "overwrite existing bottom levels" to Unchecked by default
