### ISSUE TITLE
Disable topological editing when editing channel vertices

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#219]

**Comment by leendertvanwolfswinkel** [comment]
This does not work as I would like it to work

This is how it works now:
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXVvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0dd75018788e05cd94a5baa3ac08a4ef1a93b00/Topological%20editing%20not%20disabled%20when%20editing%20channel%20vertices.mp4)

This is how I want it to work:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOStvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4029c59bd39ce71212bd1acdf3d32a9553bf84c4/Topological%20editing%20disabled%20when%20editing%20channel%20vertices.mp4)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Reported issues should be fixed now.
