### ISSUE TITLE
Allow copying data from cross-section table, friction table, vegetation table

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#229]

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I tested, but something goes wrong. When I use copy, it copies the data to the clipboard as a tab separated table, but pasting only works if there is a comma separated table on the clipboard; if I manually replace tabs by comma's in Notepad, it works.

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Changes applied.

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I now get the following error: 
```
AttributeError: 'bool' object has no attribute 'join' 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\Schema 219/python/plugins\threedi_schematisation_editor\forms\custom_forms.py", line 697, in copy_table_rows
    clipboard_values = "\n".join([separator.join(row_values) for row_values in cross_section_table_values])
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\Schema 219/python/plugins\threedi_schematisation_editor\forms\custom_forms.py", line 697, in 
    clipboard_values = "\n".join([separator.join(row_values) for row_values in cross_section_table_values])
AttributeError: 'bool' object has no attribute 'join'
```

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk10QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe5fdb3686ba1dd783214ab3b8942e4637074448/error%20when%20copying%20cross%20section%20table.mp4)
