### ISSUE TITLE
Allow external plugins/scripts to tell the Schematisation Editor to load a specific sqlite or geopackage file as active schematisation

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#238]
Use cases:
- Let 3Di Models & Simulations plugin load a schematisation after it has been created, downloaded, or activated
- Let a plugin that one of our clients has developed do the same

**Comment by leendertvanwolfswinkel** [comment]
@ldebek it works great, but I think it would be nice if we can ask users if they want to open the schematisation. I think we there are/were already dialogs that were shown when creation, download, or activation of the schematisation succeeded? Can we add a "Load from Spatialite" button to those dialogs?

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Actully download and creating new schematisation are using message bars, so adding extra dialog with question if user wants to load schematisation will be a simplest and most reasonable approach atm.

**Comment by leendertvanwolfswinkel** [comment]
@ldebek tested again, I think this is great. please merge
