### ISSUE TITLE
Importing vector data from external sources

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-schematisation-editor#28]
See shapefile and sqlite in this zip file: https://nelenschuurmans.sharepoint.com/:u:/r/sites/Lutra/Gedeelde%20documenten/General/ssw_almere_deelgebied5.zip?csf=1&web=1&e=0EZ3Wp

User (Ivar): "To efficiently add new pipes I directly copy pasted the shapefile with sewage pipes in the Pipe table. It is only partly processed. New connection nodes and manholes are made in some locations, but not everywhere. When I save the layers, everything _seems_ fine (no error messages), but actually a lot of connection nodes and manholes are missing. When exporting to spatialite, it gives an error because there are missing connection nodes. The result is that all pipes are being thrown away (and some cross sections I believe)."

Things I (Leendert) noticed:
- Most lines in the shapefile contain > 2 vertices. Connection nodes and manholes are created only on the 'in between' vertices, not on start- and endpoints.
- None of the other properties are copied from the pipes/manholes that the pasted pipes connect to

Copy-pasting features should have the same effect as drawing new features. This applies to all layers, not only for pipes.

Related: #63

**Comment by leendertvanwolfswinkel** [comment]
- Also include option to update existing feature attributes from another layers attribute table, matching (joining) features by a user-chosen field
- Pay special attention to importing cross section data, esp. tabulated data

**Comment by leendertvanwolfswinkel** [comment]
replaced by vector data importers
