### ISSUE TITLE
Add 'migrate now' button to "spatialite database schema version is not up to date" popup

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#50]
Current popup looks like this:

![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/26224299/168233140-75428911-c990-4d02-bae5-4792ad4f1e09.png)

Instead of "Please migrate your spatialite to the current schema version and try again.", text should read "Would you like to migrate your spatialite to the current schema version?"

Next to the OK button add Cancel button. Clicking OK should perform the migration. Preferably, also continue loading from spatialite after migration has completed succesfully.

**Comment by leendertvanwolfswinkel** [comment]
use threedi_modelchecker that is delivered / installed by ThreeDiToolbox (cf. Models & Simulations)

**Comment by ldebek** [comment]
Changes on branch: https://github.com/nens/threedi-schematisation-editor/tree/migration_on_the_fly

**Comment by leendertvanwolfswinkel** [comment]
Tested. Excellent workflow. Please merge with master
