### ISSUE TITLE
When using 'Save As', data should be saved to an empty spatialite that is delivered with the plugin

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-schematisation-editor#6]
"I try to save spatialite, and get the message 'test.sqlite File not found. Check the name and try again.' Would be nice to be able to store changes in a non-existing sqlite. It is counterintuitive that I have to save a file, but in the next step you need to select an existing file"
[Emiel]

**Comment by leendertvanwolfswinkel** [comment]
Will not implement
