### ISSUE TITLE
YZ Profile importer

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-schematisation-editor#63]
- [ ] https://github.com/nens/servicedesk-issue-only/issues/61

### 3Di component

Schematisation Editor

### What happened?

For a specific project, Stijn created a script to load profiles into an existing 3di model. Alexander and Leendert requested him to make a feature request. He has send the python script . 
[Script.zip](https://github.com/nens/threedi-schematisation-editor/files/9028533/c6a9864f-d14c-43a3-9b12-64ca19f4bb2b.zip)

Input and output data for testing:
[Files from Stijn.zip](https://github.com/nens/threedi-schematisation-editor/files/9039861/Files.from.Stijn.zip)

the script was made by using the threedi_raster_edits. The script makes cross section definitions and locations, edits the channel with a vertex at the cs location and deletes old cross sections. 

The proposal is to make this a feature of the MI/processing tools, so the user can upload a csv file with profiles (name, distance, z) and coordinates.

**Comment by Overmeen** [comment]
Input and output data for testing:
https://nelenschuurmans-my.sharepoint.com/:f:/g/personal/stijn_overmeen_nelen-schuurmans_nl/Eu40MyVpLrdKmExijOIE2XsBLtzp3OZI0PUOYuLaItpNoA?e=UgiS91

**Comment by Overmeen** [comment]
https://github.com/nens/threedi-model-edits/tree/main/threedi_model_edits/cross_section_definitions

Ik heb hem nu ook beschikbaar gemaakt als command-line tool

**Comment by leendertvanwolfswinkel** [comment]
No longer relevant as the current plan is to implement it in `threedi-tables`: https://github.com/nens/threedi-tables/issues/205
