### ISSUE TITLE
GPKG to Spatialite: add validity check on cross_section_table inputs

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-schematisation-editor#70]
- [ ] https://github.com/nens/servicedesk-issue-only/issues/96

If the geopackage `cross_section_table` input cannot be correctly parsed to width / height series in the spatialite, data can be lost. Some examples:

1. empty cross section table (`NULL`)
2. cross section tables with extra blank line
3. cross section table with space after comma
4. cross section table with a . in stead of , between width and height

Suggested solution:
- [x] Make conversion algorithm more robust, so that cases like 1, 2, and 3 are handled correctly
- [x] Check validity of this input before starting export. If not valid, show popup message to user. 
- [x] Implement #64 

"Saving to Spatialite failed. The following features have cross sections with incorrect table inputs: 
Cross section location {ids}
Culvert {ids}
Orifice {ids}
Pipe {ids}
Weir {ids}"

**Comment by leendertvanwolfswinkel** [comment]
I tested it. Test results:
- Performance for 'Save to spatialite' has deteriorated quiet a bit: QGIS freezes for a while and the user does not know what is going on.
- When I have no active edit sessions and use Save to spatialite, I get a lot of these popups: 
![image](https://user-images.githubusercontent.com/26224299/191749887-785c3b5e-ce9b-43eb-9bfe-5b0073a8b9a4.png)
Not only for Manhole, but also for Weir, Culvert, Orifice, Pipe, Manhole (again), Manhole (again), Manhole (again). And than it works
- If I add a blank line at the end of my input, I get `Saving to Spatialite failed. The following features have cross sections with incorrect table inputs`. I think this could be auto-fixed quite easily?
- If saving to Spatialite fails, all layers remain in edit mode
- If the input is `0,2.5\n1.5,2.5\n1.5,0`, save to spatialite fails. I think both that input (without spaces) and `0, 2.5\n1.5, 2.5\n1.5, 0` (with spaces) should be accepted and correctly parsed. `0, 2,5\n1,5, 2,5\n1,5, 0` does not have to be accepted
-  If the table input is empty, at the end of the Save to Spatialite process, I get this error:

```
ValueError: not enough values to unpack (expected 2, got 1) 
Traceback (most recent call last):
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\Release candidates June 2022/python/plugins\threedi_schematisation_editor\__init__.py", line 195, in save_to_default
    self.save_to_spatialite(pick_destination=False)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\Release candidates June 2022/python/plugins\threedi_schematisation_editor\__init__.py", line 243, in save_to_spatialite
    converter.export_all_model_data()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\Release candidates June 2022/python/plugins\threedi_schematisation_editor\conversion.py", line 706, in export_all_model_data
    self.export_cross_section_definition_data()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\Release candidates June 2022/python/plugins\threedi_schematisation_editor\conversion.py", line 611, in export_cross_section_definition_data
    height_values, width_values = list(zip(*parsed_table))
ValueError: not enough values to unpack (expected 2, got 1)
```

-

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Those 2 issues should be solved now.

**Comment by leendertvanwolfswinkel** [comment]
Both issues are solved, but now I get several "Do you want to save changes to the layer Manhole" popups again (I think four times, between data validation and saving to spatialite.

This also happens if I toggle editing on for the Pipe layer and then off again, even when I haven't edited anything.

**Comment by leendertvanwolfswinkel** [comment]
More info to reproduce the issue:

- Load the following spatialite: [Hekerbeek na maatregelen Gebiedsbreed T25.zip](https://github.com/nens/threedi-schematisation-editor/files/9696181/Hekerbeek.na.maatregelen.Gebiedsbreed.T25.zip)
- Use Identify tool to open attribute form for Pipe with ID 18891
- Start editing
- Stop editing
