### ISSUE TITLE
Enable/disable the width, height and table widgets based cross section shape

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#78]
Depending on the selected shape, some widgets (and their labels and X buttons) should be enabled / disabled. The following list shows the widgets that should be _enabled_ for each shape:
- None: None
- Circle: Width. Change name of the label to "Diameter [m]"
- Egg: Width.
- Open rectangle: Width
- Closed rectangle: Width, Height
- Tabulated rectangle: Table
- Tabulated trapezium: Table

This applies to the layers Weir, Orifice, Culvert, Pipe and Cross section location

**Comment by leendertvanwolfswinkel** [comment]
@ldebek I changed the ticket to match the new Open rectangle / Closed rectangle categories

**Comment by ldebek** [comment]
Fix available at branch: `issue_78_fix`

**Comment by leendertvanwolfswinkel** [comment]
Perfect, please merge
