### ISSUE TITLE
Add units and help text to attributes

### ISSUE THREAD

**Issue by Patrick-Nijman** [nens/threedi-schematisation-editor#8]
Would be nice to have unit specified in form (i.e. capacity = L/min) and a more extensive help text on hover/click with the explanation for each attribute as listed in the database overview (https://docs.3di.live/_downloads/84a660f75b3e8f891f1cd6c5f0b550f8/database-overview.pdf)

**Comment by leendertvanwolfswinkel** [comment]
Added the units. More documentation will be added later, but in a different way (not using tooltips)
