### ISSUE TITLE
Save to spatialite empties 'width' column in some cases

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-schematisation-editor#86]
reproduction is relatively easy:

Take this model:
https://management.staging.3di.live/schematisations/442/5777
Load it in the schematisation editor.
Save to spatialite
upload and you'll get this:
https://management.staging.3di.live/schematisations/442/5778

Maybe there are more difference but the cross section width is crucial for calculations

**Comment by leendertvanwolfswinkel** [comment]
Test sqlite: 
[testing cross sections.zip](https://github.com/nens/threedi-schematisation-editor/files/10042983/testing.cross.sections.zip)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Fix available on the master branch.

**Comment by leendertvanwolfswinkel** [comment]
I had to set the schema version back to 209 to make it work, but it works now. I created a PR for schema version 210; we will bring schema version 210 to production soon, but not yet
