### ISSUE TITLE
Breaches and exchange lines in the Schematisation Editor

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#92]
3Di Schematisation Editor:
- [x] Add a new layer group "1D2D Exchange"
- [x] Add layer potential_breach (name in layer panel: "Potential breach") in the group "1D2D Exchange"
- [x] When digitizing a new potential_breach, the start vertex should snap to a channel or connection node (preference for connection node if user moves mouse <= 1m from connection node), the end vertex to an exchange_line; the line should have exactly 2 vertices; any extra in-between vertices should be ignored. The attribute `channel_id` should be filled in automatically, based on the channel to which the breach was snapped.
- [x] Add layer exchange_line (name in layer panel: "Exchange line") in the group "1D2D Exchange"
- [x] Create styling file(s) for Potential breach
- [x] Create styling file(s) for Exchange line
- [x] Create SQLite -> Geopackage import routine for importing v2_potential_breach to potential_breach
- [x] Create SQLite -> Geopackage import routine for importing v2_exchange_line to exchange_line
- [x] Create Geopackage -> SQLite export routine for exporting potential_breach to v2_potential_breach
- [x] Create Geopackage -> SQLite export routine for importing exchange_line to v2_exchange_line
- [x] Upgrade required schema version to 214

**Comment by leendertvanwolfswinkel** [comment]
Styling files available here: [style.zip](https://github.com/nens/threedi-schematisation-editor/files/10225814/style.zip)

**Comment by leendertvanwolfswinkel** [comment]
Layer order should be: 
![image](https://user-images.githubusercontent.com/26224299/207545765-ad903142-7e53-45c1-81ee-6c707fa15e4b.png)

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Could you please provide me (or point me to) example schematisation .sqlite file with a new feature types?

**Comment by leendertvanwolfswinkel** [comment]
If you migrate a spatialite using the newest version of threedi-schema (which has been separated out from threedi-modelchecker), the tables will be created

**Comment by ldebek** [comment]
@leendertvanwolfswinkel But that won't give me any features to import right? But anyway - is it confirmed that `threedi-schema` module need to be added to the plugins dependencies?

**Comment by leendertvanwolfswinkel** [comment]
First question: I have asked @caspervdw if he can provide an example schematisation with features in the potential_breach and exchange_line tables.

Second question: yes

**Comment by leendertvanwolfswinkel** [comment]
@ldebek you can use this sqlite for testing the breaches. I'm not sure if the v2_exchange_line table contains any features, but you can just add a few. They are supposed to be drawn more or less parallel to the channel they belong to, with a maximum of 1 exchange line per channel if the channel's calculation type is 'connected', or 2 if the calculation type is 'double connected'

[v2_bergermeer.zip](https://github.com/nens/threedi-schematisation-editor/files/10511115/v2_bergermeer.zip)

**Comment by ldebek** [comment]
PR: https://github.com/nens/threedi-schematisation-editor/pull/111

**Comment by leendertvanwolfswinkel** [comment]
Tested it and it all seems to work great. However, some important fixes are needed in the attribute forms

- [ ] In the attribute form of Potential Breach, remove the underscore from "Exchange_level [m]"
- [ ] In the attribute form of Exchange line, remove the underscore from "Exchange_level [m]"
- [ ] Give 3 decimals to the input widget for exchange level (I want to be able to fill in 3.342) in the attribute forms for Potential Breach and Exchange line
- [ ] Same for Max breach depth
- [ ] Add Display name to the Potential breach attribute form
- [ ] Channel id of Exchange line should be editable in attribute form
- [ ] Change the group order to:
- 1D
- 1D2D
- 2D
- etc

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Requested fixes applied.

**Comment by leendertvanwolfswinkel** [comment]
Excellent
