### ISSUE TITLE
Fix 'cross-section' style of Channel layer for tabulated profiles

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schematisation-editor#96]
The size of the marker should be data-defined and equal to the max width of the cross section.
This max width is currently already calculated using the custom function `cross_section_label()`
My suggestion is to add and expose custom functions `cross_section_max_height()` and `cross_section_max_width()` that can be used in stylings.

**Comment by leendertvanwolfswinkel** [comment]
Also make these functions deal with the new cross section shapes (YZ, Inverted Egg, Open Rectangle)

**Comment by leendertvanwolfswinkel** [comment]
0: Closed rectangle
w: {cross_section_width}
h: {cross_section_height}
--------------
7: YZ
w: {max y}
h: {max z}
--------------

8: Inverted egg
w: {cross_section_width} 
h: {1.5*cross_section_width}

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Requested changes applied.
